# Generated by Django 4.0.4 on 2023-12-13 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('academic_degree', models.CharField(choices=[('AS', 'Ассистент'), ('ST', 'Старший преподаватель'), ('DC', 'Доцент'), ('PR', 'Профессор')], max_length=2, verbose_name='Учёная степень')),
                ('department_head', models.BooleanField(default=False, verbose_name='Заведующий кафедрой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=7, verbose_name='Номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('question_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(choices=[('08:30-10:00', 'Первая пара'), ('10:10-11:40', 'Вторая пара'), ('11:50-13:20', 'Третья пара'), ('13:50-15:20', 'Четвёртая пара'), ('15:30-17:00', 'Пятая пара'), ('17:10-18:40', 'Шестая пара'), ('18:50-20:20', 'Седьмая пара'), ('20:30-22:00', 'Восьмая пара')], max_length=11, verbose_name='Порядок пары')),
                ('day', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота')], max_length=3, verbose_name='День недели')),
                ('even_week', models.BooleanField(verbose_name='Четная неделя')),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_ai_info.educator')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_ai_info.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_ai_info.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reply_datetime', models.DateTimeField(auto_now_add=True)),
                ('author_educator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is_ai_info.educator')),
                ('author_student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is_ai_info.student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_ai_info.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is_ai_info.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='is_ai_info.educator'),
        ),
    ]
